# port settings you can change port number here.
server:
  port: 8080


# turn off/on the server
spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/customer
    username: benny
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

  main:
    web-application-type: servlet